stages:
  - build
  - lint
  - test
  - deploy

build:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG -t $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE:latest
  rules:
    - exists: 
      - $SKIP_BUILD

lint:
  stage: lint
  image: python:3.9
  before_script:
    - pip install -r requirements.txt
  script:
    - python -m pip install --upgrade pip
    - pip install pep8
    - pep8 game.py
  allow_failure: true
  rules:
    - exists: 
      - $SKIP_LINT

unit_tests:
  stage: test
  image: python:3.9
  before_script:
    - pip install -r requirements.txt
  script:
    python -m unittest discover -p 'test*.py'
  rules:
    - exists: 
      - $SKIP_TEST

# Placeholder
deploy:
  stage: deploy
  script:
    - echo "Deploying..."
  rules:
    - exists: 
      - $SKIP_DEPLOY
